stages:
  - build
  - deploy

# Cache Gradle dependencies to speed up builds
cache:
  key: gradle-cache
  paths:
    - .gradle/wrapper/
    - .gradle/caches/

# Build stage
build:
  stage: build
  image: raatiniemi/android-environment:jdk-17-android-35-latest  # Using Gradle with JDK 11
  script:
    - chmod +x gradlew
    - ./gradlew make makePluginsJson
  artifacts:
    paths:
      - "**/build/*.cs3"
      - "**/build/plugins.json"
    expire_in: 1 week

# Deploy stage to upload artifacts to GitLab registry
deploy:
  stage: deploy
  image: curlimages/curl:latest
  script:
    - ls -l build/
    - ls -l
  only:
    - main  # Only deploy when changes are pushed to the main branch
  dependencies:
    - build